default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: credit_risk_app_development

test:
  <<: *default
  database: credit_risk_app_test

production:
  <<: *default
  database: credit_risk_app_production
  username: credit_risk_app
  password: <%= ENV["CREDIT_RISK_APP_DATABASE_PASSWORD"] %>
